name: Full history calendar
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.calendar.full.svg
  token: ${{ github.token }}
  base: ""
  plugin_calendar: yes
  plugin_calendar_limit: 0
